export const ActionTypes = {
    SET_STUDENTS: "SET_STUDENTS",
    GET_STUDENT: "GET_STUDENT",
    EDIT_STUDENT: "EDIT_STUDENT",
    REMOVE_STUDENTS: "REMOVE_STUDENTS",

    SET_CLASSROOM: "SET_CLASSROOM",
    GET_CLASSROOM: "GET_CLASSROOM",
    DELETE_CLASSROOM: "DELETE_CLASSROOM",
    EDIT_CLASSROOM: "EDIT_CLASSROOM", 

    SET_SUBJECT: "SET_SUBJECT",
    GET_SUBJECT: "GET_SUBJECT",
    DELETE_SUBJECT: "DELETE_SUBJECT",
    EDIT_SUBJECT: "EDIT_SUBJECT", 

    SET_TEACHERS: "SET_TEACHERS",
    GET_TEACHERS: "GET_TEACHERS",
    DELETE_TEACHERS: "DELETE_TEACHERS",
    EDIT_TEACHERS: "EDIT_TEACHERS",

    SET_ALLOCATE_CLASSROOM: "SET_ALLOCATE_CLASSROOM",
    GET_ALLOCATE_CLASSROOM: "GET_ALLOCATE_CLASSROOM",
    DELETE_ALLOCATE_CLASSROOM: "DELETE_ALLOCATE_CLASSROOM",
    EDIT_ALLOCATE_CLASSROOM: "EDIT_ALLOCATE_CLASSROOM",

    SET_ALLOCATE_SUBJECT: "SET_ALLOCATE_SUBJECT",
    GET_ALLOCATE_SUBJECT: "GET_ALLOCATE_SUBJECT",
    DELETE_ALLOCATE_SUBJECT: "DELETE_ALLOCATE_SUBJECT",
    EDIT_ALLOCATE_SUBJECT: "EDIT_ALLOCATE_SUBJECT",

    SET_STUDENT_DETAILS: "SET_STUDENT_DETAILS",
    GET_STUDENT_DETAILS: "GET_STUDENT_DETAILS",
    DELETE_STUDENT_DETAILS: "DELETE_STUDENT_DETAILS",
    EDIT_STUDENT_DETAILS: "EDIT_STUDENT_DETAILS",
}